### PR TITLE
Invite volunteers

### PR DESCRIPTION
**Pull request by karbmk**
Invite volunteers

### CODE REVIEW

**Comment by karbmk** [comment]
@nickolashe @dannypernik Take a look at the invite-volunteers module. Please do review and provide feedback for the same.

**Comment by nickolashe** [comment]
@karbmk this PR contains (by virtue of merging) another set of changes that have not been merged to develop yet. lets use a separate branch for each feature and make sure it is synced with develop only

**Comment by nickolashe** [comment]
please open another PR with the changes for invite-volunteers only

**Comment by karbmk** [comment]
Ok. Got it

**Pull request closed without merging**
