### PR TITLE
New email confirmation pages

### PR DESCRIPTION
**Pull request by dannypernik**
Home signup should now direct to check-email.html and link in email still goes to confirm-account.html.

### CODE REVIEW

**Comment by dannypernik** [comment]
@nickolashe eh I didn't really want to bring all these changes into this PR. I meant to just use the new design of check-email and confirm-account. Not sure how to do that

**Comment by nickolashe** [comment]
@dannypernik to have just these changes you'd need to create a branch off develop and commit to it

**Comment by nickolashe** [comment]
most likely you brached off another branch of yours where you were working on other changes

**Comment by dannypernik** [comment]
Oh nice. That's helpful to know

**Pull request closed without merging**
