### PR TITLE
Password reset

### PR DESCRIPTION
**Pull request by tsiology**
New password reset functionality can be requested from login page. If user already has a valid password, they will be emailed a link to the reset-password template.

### CODE REVIEW

**Comment by nickolashe** [comment]
Can we fix the links and add the token to the url pls

**Comment by tsiology** [comment]
@nickolashe Fixed redirections and added token verification in process_reset_password.

**Comment by nickolashe** [comment]
@tsiology thanks, will give this a try and let you know

**Comment by nickolashe** [comment]
@tsiology looks good

**Pull request merged**
