### PR TITLE
change upcoming-projects to upcoming-events, remove time-tracker from profile

### PR DESCRIPTION
**Pull request by dannypernik**

### CODE REVIEW

**Comment by nickolashe** [comment]
@dannypernik notice that even once this is merged we'll still need to merge master into develop to keep them in sync

**Comment by nickolashe** [comment]
so from that point of view I think its just more consistent to always open PR's against develop

**Comment by nickolashe** [comment]
@dannypernik what was the problem with renaming the view again?

**Comment by nickolashe** [comment]
@dannypernik next time can you please post a summary for the PR here of a similar form to this:
https://opencurrents.slack.com/archives/D3VLYUDFZ/p1499735794399252

**Comment by nickolashe** [comment]
@dannypernik I can't find the change that "removes time-tracker from profile"

**Comment by dannypernik** [comment]
@nickolashe gotcha, will add PR explanation and merge to develop first next time. I guess I just wanted to get these more immediate changes approved without bringing in all of the develop changes.

Hmm I got an error that mentioned that some view or module wasn't found, I think.

time-tracker was removed here by removing the popup with the option: https://github.com/opencurrents/opencurrents/pull/146/commits/6ca2057bff898d0d10cb904dc18f14182919a433#diff-2a4ce436dcc80c02e96b2a7ed00b75bbR24

**Comment by nickolashe** [comment]
got it

**Comment by dannypernik** [comment]
@nickolashe does the thought of merging directly to master for urgent changes justify doing it? Or is there a way to pass along changes of 1 PR through develop into master while bypassing the rest of develop?

**Comment by nickolashe** [comment]
for critical changes it makes sense, yes

**Pull request merged**
