### PR TITLE
Create event; Invite volunteers; Counts

### PR DESCRIPTION
**Pull request by tsiology**
Adding urls for admin-profile with num_events and num_vols extra args.

Adding url for invite-volunteers with num_events extra arg passed from create-event

Adding logic in admin-profile to display status msg depending on number of event locations created or volunteers invited.

num_events is working from AdminProfileView Event model checking, num_vols is working from invite-volunteers url arg.

### CODE REVIEW

**Comment by tsiology** [comment]
I will investigate using context data to pass num_events from create-event -> invite-volunteers -> admin-profile. Currently using url and ran into conflicts.

**Comment by tsiology** [comment]
@nickolashe @dannypernik admin-profile status msg now works with num_events by checking Event fields in AdminProfileView function and num_vols url arg passed from invite-volunteers. Please review implementation and confirm behavior. Thanks!

**Comment by nickolashe** [comment]
make sure the splitting of volunteer emails works in all cases

**Comment by nickolashe** [comment]
@karbmk @tsiology we can't merge this one as is; there are quite a few conflicts in `views.py`

**Comment by tsiology** [comment]
@karbmk @nickolashe Conflicts in view.py caused by ApproveHoursView function cleanup in Develop have been resolved.

**Comment by nickolashe** [comment]
@karbmk @tsiology I am getting a wrong count (of 3) when inviting 2 comma-separated emails. Can you double-check please?

**Comment by nickolashe** [comment]
Also, lets change the message to "registered X volunteers to the event" instead of "invited to the platform", since we are not inviting existing ones.

**Comment by karbmk** [comment]
Hi @nickolashe , Is the wrong count in copy/paste emails?

**Comment by nickolashe** [comment]
copy/paste yes, after creating an event

**Comment by karbmk** [comment]
Did you by any chance added an extra comma at the end?

**Comment by nickolashe** [comment]
@karbmk nope, please see the screenshots below:

screen shot 2017-08-08 at 10 35 30 am

screen shot 2017-08-08 at 10 35 47 am

**Comment by nickolashe** [comment]
@karbmk @tsiology can you make sure develop is merged too, pls

**Comment by nickolashe** [comment]
@karbmk i am still seeing the same error

**Comment by dannypernik** [comment]
@tsiology or @karbmk what's this input field for? 

https://github.com/opencurrents/opencurrents/blob/04434d3af7f460048d4a8bc2c0ef475d28482104/openCurrents/templates/invite-volunteers.html#L64

**Comment by karbmk** [comment]
@nickolashe , I had the error once I merged but I fixed it and pushed the changes. It's a one line change. I will check again on that though.

@dannypernik , That is the field to store the comma separated emails and if present send to the views else nothing will happen.

**Comment by karbmk** [comment]
Hi @nickolashe , I am not able to reproduce the wrong volunteer number after the merge and fix. Can you tell me any specifics if that's ok. I might be missing something here!

**Comment by nickolashe** [comment]
@karbmk when you enter two emails separated by a comma, what is the count you are seeing? not sure if this is of relevance, but one of the emails i am entering is that of the admin.

**Comment by karbmk** [comment]
I am getting 2 volunteers invited. I also checked in tim's system with the latest pull. working fine. But I don't know if the admins email would cause any problem. I will take a look on that and update you.

**Comment by nickolashe** [comment]
@karbmk @tsiology ok, should we troubleshoot this live then?

**Comment by dannypernik** [comment]
@nickolashe @karbmk were either of you adding the same email that you were logged in to? This seems to be the issue Shavone was having - she couldn't send an email to herself and we're not clear why. Does Mandrill prevent an email being sent with "To" and "Reply-to" as the same email?

**Comment by karbmk** [comment]
@nickolashe , Sure we should. We can troubleshoot some time you are available. 

@dannypernik , We might want to look at that so as to make sure we are doing it properly. But I invited myself to an event and there was no problem with that.

**Comment by nickolashe** [comment]
I believe there is not any restriction w.r.t. the matching To and Reply-To fields

**Pull request merged**
