### PR TITLE
Home base

### PR DESCRIPTION
**Pull request by dannypernik**

### CODE REVIEW

**Comment by nickolashe** [comment]
changed the base branch, this looks good now

**Comment by nickolashe** [comment]
we can merge upon resolving the conflict

**Comment by nickolashe** [comment]
@tevtonez can you comment on the test failure above please

**Comment by dannypernik** [comment]
@tevtonez doesn't look like you can see the circleci test failures now that I've merged the branch - here are the 4:
```
FAIL: test_logged_hours_decline (openCurrents.tests.test_approve_hours.TestApproveHoursTwoWeeks)
FAIL: test_logged_hours_accept (openCurrents.tests.test_approve_hours.TestApproveHoursTwoWeeks)
FAIL: test_logged_hours_declined (openCurrents.tests.test_approve_hours.TestApproveHoursOneWeek)
FAIL: test_logged_hours_accept (openCurrents.tests.test_approve_hours.TestApproveHoursOneWeek)
```

**Comment by tevtonez** [comment]
@nickolashe currently only one test is failing on develop for me:
screenshot 2018-01-08 11 11 15
and I fixed it in 873064e today.

**Pull request merged**
