### PR TITLE
adding existing users to event when invited

### PR DESCRIPTION
**Pull request by tevtonez**

### CODE REVIEW

**Comment by nickolashe** [comment]
@tevtonez is this WIP?

**Comment by tevtonez** [comment]
@nickolashe 
no it's ready to be merged

**Comment by nickolashe** [comment]
@tevtonez ok, thanks. lets remember to move to the proper pipeline in such case

**Comment by tevtonez** [comment]
@nickolashe ugh, sorry, I moved it to "PR needs backend " instead of "PR Ready to merge"

**Pull request merged**
