### PR TITLE
Check-email page with email displayed after user registers

### PR DESCRIPTION
**Pull request by tsiology**

### CODE REVIEW

**Comment by nickolashe** [comment]
@tsiology is this working now?

**Comment by tsiology** [comment]
Yes, with these updates new users are redirected to check-email page which reports the email we sent to

**Comment by tsiology** [comment]
Still work to be done on the resend email button on the check-email page

**Comment by tsiology** [comment]
@nickolashe I'm close to having the Resend button implemented. Before committing that, can we merge this current small PR which just finalizes the check-email redirection?

**Comment by nickolashe** [comment]
@tsiology sure, please go ahead and merge it

**Pull request merged**
