### PR TITLE
Time tracker issue 327

### PR DESCRIPTION
**Pull request by karbmk**
Files changed:
1. views.py

### CODE REVIEW

**Comment by nickolashe** [comment]
@karbmk good work!

**Comment by dannypernik** [comment]
@nickolashe @karbmk can we delete this branch? How should we ensure we're deleting branches whenever it's safe and sensible to do so? Perhaps we can decide which branches we want to keep, then delete any others when they are merged?

**Comment by nickolashe** [comment]
we should delete feature-specific branches upon merging

**Comment by dannypernik** [comment]
@tsiology see last couple comments FYI

**Pull request merged**
