### PR TITLE
Kostya time tracker update

### PR DESCRIPTION
**Pull request by tevtonez**

### CODE REVIEW

**Comment by tevtonez** [comment]
Form fixes are implemented as per our discussions today, and unittests are finished. No skipping tests for this feature anymore.

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach lets retest time-tracker

**Comment by dannypernik** [comment]
@tevtonez @nickolashe looks like status messages are a little weird - first, these three on time-tracker popped up when selecting "Someone else" and using email drpernik@gmail.com as admin coordinator:

screen shot 2017-12-19 at 10 37 28 pm
screen shot 2017-12-19 at 10 35 52 pm
screen shot 2017-12-19 at 10 36 50 pm

On my local system, drpernik@gmail.com is actually an admin of Keep Austin Beautiful. (Bike Austin and Great Deeds were the orgs selected on the top 2 tests above.) I don't think it's necessary to tell user which org the email is connected with. Instead, a status "drpernik@gmail.com is already associated with another organization and cannot approve hours for (selected org)". (Also exclude org ID from status).

As for the last status message above, I'm not clear on why I received it or what it's supposed to mean. I was actually just trying to replicate the first error when I saw it.

**Comment by dannypernik** [comment]
When testing "Request Currents from another organization", I received the following after recording hours 2 days in the past:
screen shot 2017-12-19 at 10 51 04 pm

**Comment by tevtonez** [comment]
Regarding the ID part in Orgs' names:
screenshot 2017-12-20 22 49 22
The orgs names include their IDs by default.

**Comment by dannypernik** [comment]
@tevtonez I believe we have variable `{{ orgname }}` available to all templates which excludes npf and id.

**Comment by tevtonez** [comment]
@dannypernik 
The message "You can submit hours for review by organization admin\'s registered on openCurrents. You can also invite new admins to the platform.'" was there before and it appears if you select "I'm not sure" option.
I agree it shouldn't be in green color. Please provide the message that should be displayed if user selected "I'm not sure" option. Thanks.

**Comment by dannypernik** [comment]
@tevtonez I'm pretty sure we decided to remove the "not sure" option, and I've now done so on develop branch. @MaxTattenbach @nickolashe can you confirm this? I found a commit where I removed the no-admin-popup, but had forgotten to remove the option from the dropdown.

**Comment by dannypernik** [comment]
@tevtonez fyi, I was seeing the "You can submit hours for review..." message after trying to submit form with "Someone else" selected.

**Comment by tevtonez** [comment]
to all:
"not sure" option has been removed from backend

**Pull request merged**
