### PR TITLE
HTML refactoring WIP

### PR DESCRIPTION
**Pull request by dannypernik**
Feel free to review at any time and suggest changes, I'll add `review_requested` when I've finished a first round

### CODE REVIEW

**Comment by nickolashe** [comment]
@dannypernik can you provide a summary of changes please

**Comment by dannypernik** [comment]
@nickolashe I've refactored all templates that use base.html as its base template. This includes all html files other than home, nonprofit, volunteer, business, org-admin, biz-admin, and profile. The last three will use admin as base layout, and I've essentially used biz-admin as the default content for the admin layout. Wanting to know if this makes sense. Other changes in this PR are a result of pulling `edit_event_form`.

**Comment by nickolashe** [comment]
why admin is not extending base?

**Comment by nickolashe** [comment]
@dannypernik i think its best to find some time to walk through this one together

**Comment by dannypernik** [comment]
Good call, didn't think of that. admin now extends base. Sounds good to walk through this together.

**Comment by nickolashe** [comment]
@dannypernik how's the progress here?

**Comment by nickolashe** [comment]
looks like lots of conflicts

**Comment by dannypernik** [comment]
@nickolashe we discussed going through this together.

**Pull request merged**
