### PR TITLE
Kostya profile additions

### PR DESCRIPTION
**Pull request by tevtonez**
@nickolashe please review float numbers formatting implementation per our yesterday's discussion, thanks!
Email parser is implemented now.

### CODE REVIEW

**Comment by nickolashe** [comment]
@tevtonez rounding looks good. just to be clear, are you done with email parsing?

**Comment by tevtonez** [comment]
@nickolashe 
> are you done with email parsing?
yes, I still recommend to show "correct" formats of emails that may be used in bulk field

**Comment by tevtonez** [comment]
oops, I accidentally pushed broken test, fixing...

**Comment by tevtonez** [comment]
The work on this branch is finished for now and can be merged...

**Comment by nickolashe** [comment]
@dannypernik what do you think on Kostya's comment above regarding email formats?

**Comment by dannypernik** [comment]
I've added a placeholder with example emails. @tevtonez will the email parser identify emails separated by newlines?

**Comment by tevtonez** [comment]
@dannypernik no, only commas are counted as a separator.

**Comment by dannypernik** [comment]
@tevtonez @nickolashe I believe we want to parse all valid emails from any text copy/pasted into bulk email box. The most pertinent example is when someone copies emails from Gmail, which displays this format: `Danny Pernik <danny@opencurrents.co>, Nicko Shestopalov <nicko@opencurrents.co>` but seems with regex we could just as easily parse emails from any text?

**Comment by tevtonez** [comment]
@dannypernik @nickolashe the request in #906 says that we should extract not only emails but first and last names (which we do currently)
Currently we're splitting string by commas and it's shouldn't be hard to split it by new lines too, but the parser may not work in cases when user accidentally provides bulk emails in format like below (note a new line between Firstname2  and Lastname2):
```
Firstname1 Lastname1 <email1@eeee.ee>, Firstname2 
Lastname2 <email2@eeee.ee>, Firstname3 Lastname3 <email2@eeee.ee>,
Firstname4 Lastname4 <email2@eeee.ee>, 
```
so limiting to only one possible format seems more preferable, since the users will have less options in this case thus the possibility to mix the options and make a mistake is lower.

**Comment by dannypernik** [comment]
@tevtonez @MaxTattenbach @nickolashe I don't believe the intention of #906 was to set user's first and last name, but simply that a user could copy names into the box and we could still parse all emails. So you can ignore all text that is not in email format.

**Comment by nickolashe** [comment]
That’s correct, we don’t need to use the data to set names.

**Comment by dannypernik** [comment]
@tevtonez reopening #906 with a more specific title

**Pull request merged**
