### PR TITLE
Issue #410 fix

### PR DESCRIPTION
**Pull request by karbmk**
added "iexact" in the query filters for ignoring the case.
built and tested for:
1. Signup
2. invite volunteers
3. Live-Dashboard

### CODE REVIEW

**Comment by dannypernik** [comment]
This is looking good. Only thing that could be improved is that the status_msg that displays on admin_profile says that 1 volunteer has been invited even if the email already exists. I'm going to create a separate issue for this (It might be related to the inconsistent counts that @nickolashe was seeing previously - for example I know that when we tested emails with `< >` around them, it considered this text a separate email and added to the count.) I dont think we need to worry about this outstanding issue right now.

**Comment by dannypernik** [comment]
Upon review, we already have an MVP issue for the status_msg, so I'll add my notes there.

**Comment by nickolashe** [comment]
@karbmk would not it be easier to always convert emails to lower case in forms clean method?

**Comment by karbmk** [comment]
You mean even while storing in the database you mean?

**Comment by nickolashe** [comment]
yes, why don't we always store all emails lower case ?

**Pull request closed without merging**
