### PR TITLE
Clear location on remove

### PR DESCRIPTION
**Pull request by dannypernik**
This erases a location input field when you click the X on a location for both create-event and edit-event.

### CODE REVIEW

**Comment by nickolashe** [comment]
@dannypernik Can you provide the changes summary please?

**Comment by nickolashe** [comment]
bump

**Comment by dannypernik** [comment]
@nickolashe done

**Comment by nickolashe** [comment]
wow github is getting smart at illustrating changes of files other than text

**Comment by nickolashe** [comment]
@dannypernik great thanks, how about resolving the conflict?

**Comment by dannypernik** [comment]
ha cool

**Pull request closed without merging**
