### PR TITLE
Google analytics; clear location

### PR DESCRIPTION
**Pull request by dannypernik**
Clear input field when clicking 'x' on a location for create-event and edit event; adding google analytics snippet; got earn-currents code working by moving approve-hours logic to separate <script>

### CODE REVIEW

**Comment by nickolashe** [comment]
@dannypernik this has conflicts

**Comment by nickolashe** [comment]
i think @karbmk already got the earn currents popup working

**Comment by dannypernik** [comment]
@nickolashe I think this is good now. Verified that earn-currents popup now pops

**Comment by nickolashe** [comment]
@dannypernik FYI, the form no longer submits upon removing a location

**Comment by nickolashe** [comment]
@dannypernik please make sure all conflicts are resolved before requesting review

**Pull request merged**
