### PR TITLE
Modifications to invite vols from event and URL param change

### PR DESCRIPTION
**Pull request by karbmk**

### CODE REVIEW

**Comment by nickolashe** [comment]
@karbmk what's the plan for switching to passing `JSON` in other places? do you think it makes sense to include this as part of this PR or another one?

**Comment by karbmk** [comment]
I think we should do it in this PR itself. Once it's merged to develop then it would be easier that all JSON implementations are applied at once.

**Comment by nickolashe** [comment]
@karbmk ok, so is this your plan then?

**Comment by karbmk** [comment]
Yes it is!

**Comment by nickolashe** [comment]
@karbmk I am removing "review requested" label since I think there are more places where we need to switch to passing `JSON`

**Comment by karbmk** [comment]
Agreed

**Comment by dannypernik** [comment]
@nickolashe @karbmk safe to delete branch?

**Pull request merged**
