### PR TITLE
Autosave correct login, conditional message for org signups, remove chat button from live-dashboard since it interferes

### PR DESCRIPTION
**Pull request by dannypernik**
Added a hidden email field with user's email autofilled so that when browser asks "Do you want to save this password" it saves with correct login details.

Also added a message that says "We have created your personal account and will be in touch" if the user registered a nonprofit or business.

### CODE REVIEW

**Comment by nickolashe** [comment]
@dannypernik can you provide the summary of changes?

**Comment by nickolashe** [comment]
@dannypernik can you merge #344 and change the conditional on the admin status message accordingly please?

**Comment by dannypernik** [comment]
screen shot 2017-08-23 at 5 42 06 pm

@nickolashe I pulled in the latest changes to `develop` branch which includes is_admin. I believe we do want `if orgid` instead of is_admin since user will not be approved yet on check-email page. However, I'm now getting the error above when signing up as a business via the popup form on /business.

**Comment by nickolashe** [comment]
This error is unrelated to org / is_admin. This most likely means csrf token is missing from the popup form.

**Comment by nickolashe** [comment]
@dannypernik what effect does org / is_admin have on the check-email page?

**Comment by dannypernik** [comment]
`if orgid = True` adds a sentence saying we've created their personal account and will be in touch.

I'm not sure what the deal is, I do have `{% csrf_token %}` in the form for the popup window in /business: 
https://github.com/opencurrents/opencurrents/blob/master/openCurrents/templates/business.html#L288

**Comment by nickolashe** [comment]
@dannypernik the popup form is working for me on the dev server. try refreshing the page and/or clearing the cache.

**Comment by nickolashe** [comment]
i think we are still providing `orgid` as well, so feel free to use that for the conditional when appropriate

**Comment by nickolashe** [comment]
@dannypernik have you been able to resolve the orgid / is_admin issue?

**Comment by nickolashe** [comment]
can we resolve the conflicts as well here

**Comment by dannypernik** [comment]
@nickolashe yes I'm using orgid to display this message since user won't be approved as admin when visiting this page. Merge conflict fixed

**Pull request merged**
