### PR TITLE
Current value to $20/Current

### PR DESCRIPTION
**Pull request by dannypernik**
#963 

@nickolashe please check that I've changed everything that needs to be changed in the JS logic on redeem-currents. Note that I'm bumping up the fee to 15% based on prior conversations now that volunteers will be getting double for their time.

### CODE REVIEW

**Comment by nickolashe** [comment]
looks good, i'll add the rest of the changes to this PR

**Comment by dannypernik** [comment]
@nickolashe great thanks

**Comment by nickolashe** [comment]
@tevtonez can you comment on the test failure above please

**Comment by nickolashe** [comment]
@dannypernik I believe that's it now. Notice I modified some of your changes to use variables instead of hardcoded values.

**Pull request merged**
