### PR TITLE
email-confirmation to volunteers

### PR DESCRIPTION
**Pull request by dannypernik**

### CODE REVIEW

**Comment by dannypernik** [comment]
@nickolashe email doesn't look to be sending to volunteer on registration. Can you see an obvious reason why not?

**Comment by nickolashe** [comment]
not really, seems like not much has changed

**Comment by nickolashe** [comment]
@dannypernik i see you added another commit. did this help address the issue?

**Comment by dannypernik** [comment]
@nickolashe no, that commit is just a starting point for issue #897 which I think makes sense to include in this PR. Please note my latest comment on that issue.

**Comment by dannypernik** [comment]
@nickolashe I'm starting over with a new branch off develop

**Pull request closed without merging**
