### PR TITLE
master funds available

### PR DESCRIPTION
**Pull request by nickolashe**

### CODE REVIEW

**Comment by dannypernik** [comment]
screen shot 2018-01-26 at 12 51 20 am

**Comment by nickolashe** [comment]
@dannypernik has this been tested?

**Comment by nickolashe** [comment]
bump

**Comment by dannypernik** [comment]
@nickolashe yes, I've verified that master currents available decreases with each special offer redeemed, and alert message appears on marketplace if all 2 Currents have been redeemed.

**Pull request merged**
